name: Build on dev branch

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Copy
              run: |
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'action@github.com'
                  git fetch
                  git checkout dev   
                  git checkout ${GITHUB_REF##*/} -- ./src

            - name: Build on dev branch
              run: |
                  git checkout dev
                  node index-dev.js

            - name: Push changes to dev branch
              run: |
                  git add src docs
                  git commit -m "Build new files"
                  git push origin dev
