name: Build on dev branch

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3.5.2

            - name: Copy source files to dev branch
              run: |
                  git checkout dev
                  git checkout main -- .
                  git add .
                  git commit -m "Update source files from main branch"
                  git push origin dev

            - name: Build on dev branch
              run: |
                  git checkout dev
                  # Run the build scripts here

            - name: Push changes to dev branch
              run: |
                  git add .
                  git commit -m "Build new files"
                  git push origin dev
