name: Build on dev branch

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Copy source files
              run: |
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'action@github.com'
                  git fetch
                  git checkout dev   
                  git checkout ${GITHUB_REF##*/} -- ./src
            - name: Build from source files
              run: |
                  git checkout dev
                  node index-dev.js
            - name: Push to dev branch
              run: |
                  git add src
                  git commit -m "Update source files ✨"
                  git add docs
                  git commit -m "Build new files 🎉"
                  git push origin dev
